---
- name: Configure base OS
  import_playbook: playbooks/00_system.yml
  tags:
    - system
- name: Install webserver
  import_playbook: playbooks/01_webserver.yml
  tags:
    - webserver
- name: Install monitoring system
  import_playbook: playbooks/02_monitoring.yml
  tags:
    - monitoring
