---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bionic
    pre_build_image: true
    image: quay.io/paulfantom/molecule-systemd:ubuntu-18.04
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    groups:
      - python3
      - prometheus
      - alertmanager
      - grafana
      - exporters
      - web
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    privileged: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  inventory:
    links:
      group_vars: ../../group_vars/
      host_vars: host_vars/
verifier:
  name: testinfra
