---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - openssh-server
        - openssh-client
    - name: Create dir
      ansible.builtin.file:
        path: "/run/sshd"
        state: directory
        mode: 0755
