---
- name: Setup HTTP server
  hosts: web
  roles:
  - caddy_ansible.caddy_ansible
  pre_tasks:
  - name: Ensure webdirs exists
    file:
      mode: '0755'
      path: "{{ item }}"
      state: directory
    with_items:
      - /var/www/demo
      - /var/www/demo/img
  - name: Ensure portal site exists
    copy:
      mode: '0644'
      src: index.html
      dest: /var/www/demo/index.html
  - name: Copy digitalocean image
    get_url:
      url: "https://github.com/prometheus/demo-site/raw/prometheus/playbooks/files/img/digitalocean.png"
      dest: "/var/www/demo/img/digitalocean.png"
      mode: 0644
