---
- name: Setup HTTP server
  hosts: web
  roles:
    - maxhoesel.caddy.caddy_server
      #   pre_tasks:
      #     - name: Ensure webdirs exists
      #       ansible.builtin.file:
      #         mode: '0755'
      #         path: "{{ item }}"
      #         state: directory
      #       loop:
      #         - /var/www/demo
      #         - /var/www/demo/img
      #     - name: Ensure portal site exists
      #       ansible.builtin.copy:
      #         mode: '0644'
      #         src: index.html
      #         dest: /var/www/demo/index.html
      #     - name: Copy digitalocean image
      #       ansible.builtin.get_url:
      #         url: "https://github.com/prometheus/demo-site/raw/prometheus/playbooks/files/img/digitalocean.png"
      #         dest: "/var/www/demo/img/digitalocean.png"
      #         mode: 0644
